# Generated by Django 4.2.5 on 2023-10-25 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bug', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='report_date',
            field=models.DateField(),
        ),
    ]
